package com.fixterminal.shared.enumerators;

public enum RxAction {
    BUY_MARKET,
    SELL_MARKET,
    CLOSE,
    REVERS,
    BUY_LIMIT,
    SELL_LIMIT,
    STOP_LOSS_SET,
    STOP_LOSS_UP,
    STOP_LOSS_DOWN,
    TAKE_PROFIT_SET,
    TAKE_PROFIT_CANCEL,
    STOP_LOSS_CANCEL,
    CANCEL_PENDING_ORDER,
    BREAK_EVENT_SET,
    TRAILING_STOP_START,
    TRAILING_STOP_STOP,

    BREAK_EVENT_AUTO_ON,
    BREAK_EVENT_AUTO_OFF,
    TRAILING_STOP_AUTO_ON,
    TRAILING_STOP_AUTO_OFF,
    SET_PARAMETER,
    SET_PARAMETER_VALUE_UP,
    SET_PARAMETER_VALUE_DOWN


}
